### ISSUE TITLE
List of category isn't working

### ISSUE THREAD

**Issue by p1-dta** [Vikka/Meteor#2]
I try to create a list of Category(BoxLayout) but something went wrong. I want to have a box with two label in it, name and description. No error raised but nothing appear where it should be one Category.

I try to change things like name of id, making it different from the self.name: StringProperty in the class, but nothing change.

in Meteor/main.py :
```
class Category(BoxLayout):
    Builder.load_file('kv_files/CollectionCard.kv')
    name: StringProperty
    description: StringProperty

    def __init__(self, name: str = 'Name', description: str= 'desc', **kwargs):
        super().__init__(**kwargs)
        self.name = StringProperty(name)
        self.description = StringProperty(description)


class MainWindow(BoxLayout):
    Builder.load_file('kv_files/MainWindow.kv')
    category = ObjectProperty(None)
```
in Meteor/kv_files/CollectionCard.kv :
```
<Category>
    name: name
    description: description
    size_hint_y: None
    height: self.parent.height/15
    row: 2
    Label:
        id: name
        text: self.parent.name.text
        size_hint_y: None
        height: self.parent.height*2/3
        text_size: self.size
        font_size: '25sp'
        markup: True
    Label:
        id: description
        text: self.parent.name.text
        size_hint_y: None
        height: self.parent.height*1/3
        text_size: self.size
        font_size: '25sp'
        markup: True
```

**Comment by p1-dta** [comment]
I tried to change the class Category and the kvlang associate to it. No raised error and some text appear : 
```
class Category(Widget):
    Builder.load_file('kv_files/CollectionCard.kv')
    name_label = ObjectProperty(None)
    description_label = ObjectProperty(None)
    name: str
    description: str

    def __init__(self, name: str = 'Name', description: str= 'desc', **kwargs):
        super().__init__(**kwargs)
        self.name = name
        self.description = description
```
```
<Category>
    BoxLayout:
        name_label: name_label
        description_label: description_label
        size_hint_y: None
        height: self.parent.height/15
        row: 2
        Label:
            id: name_label
            text: self.parent.parent.name
            size_hint_y: None
            height: self.parent.height*2/3
            text_size: self.size
            font_size: '25sp'
            markup: True
        Label:
            id: description_label
            text: self.parent.parent.name
            size_hint_y: None
            height: self.parent.height*1/3
            text_size: self.size
            font_size: '25sp'
            markup: True
```
![issue1_window](https://user-images.githubusercontent.com/9381120/50903387-a2a65c80-1458-11e9-8d1a-92be55cbaea0.PNG)

**Comment by p1-dta** [comment]
The appearance is better with the BoxLayout as super, but don't know why.
`class Category(BoxLayout):`

![issue1_window_crop](https://user-images.githubusercontent.com/9381120/50903849-c7e79a80-1459-11e9-9a40-ffd49321c1a5.PNG)

**Comment by p1-dta** [comment]
I removed the `size_hint_y` and `height` parameter in the kvlang. It fixed half of the problem.
```
<Category>
    BoxLayout:
        name_label: name_label
        description_label: description_label
        size_hint_y: None
        height: self.parent.height/15
        row: 2
        Label:
            id: name_label
            text: self.parent.parent.name
            text_size: self.size
            font_size: '25sp'
            markup: True
        Label:
            id: description_label
            text: self.parent.parent.description
            text_size: self.size
            font_size: '18sp'
            markup: True
```

![issue1_window_crop2](https://user-images.githubusercontent.com/9381120/50905139-121e4b00-145d-11e9-8586-bdcff58f6add.PNG)
